newggtheme_with_legends <- theme(
  plot.title = element_text(hjust = 0, vjust = 1, size = rel(1)), 
  panel.background = element_blank(), 
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  strip.background = element_blank(),
  panel.border = element_rect(fill = NA, colour = "black"),
  plot.background = element_blank(), 
  text = element_text(color = "gray20", size = 10), 
  axis.text = element_text(size = rel(1)), 
  axis.text.x = element_text(color = "gray20", size = rel(1.2)), 
  axis.text.y = element_text(color = "gray20", size = rel(1.2)), 
  axis.title.x = element_text(size = rel(1.3), vjust = 0), 
  axis.title.y = element_text(size = rel(1.3), vjust = 1), 
  axis.ticks.y = element_blank(), 
  axis.ticks.x = element_blank(), 
  strip.text.x = element_text(size = rel(1.5)),
  legend.position = "top",
  legend.key=element_rect(fill=NA),
  legend.title = element_blank(),
  legend.text=element_text(size=rel(1.5)),
  plot.subtitle = element_text(color = "gray20", size = rel(1.0), face="italic"),
  plot.caption = element_text(color = "dodgerblue", size = rel(1.0))
)
